### ISSUE TITLE
Do Dynamic Models work on the GPU

### ISSUE THREAD

**Issue by joshuar9** [sskorol/vosk-api-gpu#2]
Hi, I'm really interested in this project, but I haven't had a chance to play with it.

I wanted to ask a question regarding Vosk's dynamic/ static models. As I understand it, most of the models on https://alphacephei.com/vosk/models are big models that are compiled statically, meaning that in order to expand the vocabulary of words detected, for example, to add "Github" (assuming that's not already something it can output), would require recompiling to modify the dictionary and language model and have "Github" successfully detected and returned as an output. There are also models with a dynamic graph, which allow online modification of the vocabulary without the time-expensive recompiling.

I'm interested in knowing if you've gotten models with dynamic graphs working on the GPU, and if they also benefit from performance improvements. Any insight would be appreciated. 

Thanks!
Joshua Rosales

**Comment by sskorol** [comment]
@joshuar9 hi,

You can use both small and big models with GPU. But you have to either build Kaldi/Vosk with GPU support on your own or use images linked in this repo. The rebuild process doesn't affect models. You just rebuild the core API.

Small models with a dynamic graph allow increasing the probability of specified words' appearance in transcribe. However, these words should be still present in the vocabulary. On the other hand, small models consume fewer resources and are less accurate.

Big models are more accurate, don't support adaptation, and consume more resources. However, GPU gives a great performance boost in terms of latency.

Personally, I deploy Vosk to Jetson Xavier board. It works on Nano though. On the other hand, you should keep in mind that the latest versions require ~8GB RAM due to RNNLM rescoring.
